-- © 2026 iM1GHTB3DANI/danijayvv
--!strict

return table.freeze( {
	BarCount = 32.0,
	BarGap = 0.2,
	BarDecay = 0.9,
	BarMaxHeight = 8.0,
	BarColorLow = Color3.fromRGB( 0 , 0 , 255 ),
	BarColorHigh = Color3.fromRGB( 255 , 0 , 0 ),

	BarThickness = 0.5,
	BarDepth = 0.5,
	LineSpacing = 0.8,
	Pivot = Vector3.zero,
	Shape = 'Line',
	StartAngle = 0,
	Radius = 0,
	Width = 16,
	Depth = 16,

	StarPoints = 5,
	StarInnerRadius = 4,
	StarOuterRadius = 8,
	PolygonSides = 4,
	WaveFrequency = 2,
	WaveAmplitude = 4,
	ArcAngle = 180,
} )